# 텍스트 분석 - BOW(Bag of Words)

### 1. Count Vectorizer

In [1]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = ['you know I want your love. because I love you.']

In [5]:
count_vect = CountVectorizer()
count_vect.fit(corpus)
output = count_vect.transform(corpus)
output.toarray()

array([[1, 1, 2, 1, 2, 1]], dtype=int64)

In [7]:
count_vect.vocabulary_

{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}

### 불용어를 제거한 BoM

In [9]:
# 자체 제거
text = ["Family is not an important thing. It's everything."]
cvect = CountVectorizer(stop_words=['the', 'a', 'an', 'is', 'not'])
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


In [11]:
# Scikit-Learn에서 제공하는 불용어 사용
text = ["Family is not an important thing. It's everything."]
cvect = CountVectorizer(stop_words='english')
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}


In [14]:
# NLTK에서 제공하는 불용어 사용
from nltk.corpus import stopwords
sw = stopwords.words('english')
len(sw)

179

In [15]:
text = ["Family is not an important thing. It's everything."]
cvect = CountVectorizer(stop_words=sw)
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


In [16]:
def get_word(index, voca):
    for key, value in voca.items():
        if value == index:
            return key

In [20]:
get_word(3, cvect.vocabulary_)

'thing'

### N-gram

In [26]:
text = ['machine learning is fun and is not boring']
cvect = CountVectorizer(ngram_range=(0,3))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[9 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1]]
{'': 0, 'machine': 16, 'learning': 13, 'is': 8, 'fun': 5, 'and': 1, 'not': 19, 'boring': 4, 'machine learning': 17, 'learning is': 14, 'is fun': 9, 'fun and': 6, 'and is': 2, 'is not': 11, 'not boring': 20, 'machine learning is': 18, 'learning is fun': 15, 'is fun and': 10, 'fun and is': 7, 'and is not': 3, 'is not boring': 12}


In [27]:
cvect = CountVectorizer(ngram_range=(1,3))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1]]
{'machine': 15, 'learning': 12, 'is': 7, 'fun': 4, 'and': 0, 'not': 18, 'boring': 3, 'machine learning': 16, 'learning is': 13, 'is fun': 8, 'fun and': 5, 'and is': 1, 'is not': 10, 'not boring': 19, 'machine learning is': 17, 'learning is fun': 14, 'is fun and': 9, 'fun and is': 6, 'and is not': 2, 'is not boring': 11}


In [28]:
cvect = CountVectorizer(ngram_range=(2,3))
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1 1 1 1 1 1 1]]
{'machine learning': 10, 'learning is': 8, 'is fun': 4, 'fun and': 2, 'and is': 0, 'is not': 6, 'not boring': 12, 'machine learning is': 11, 'learning is fun': 9, 'is fun and': 5, 'fun and is': 3, 'and is not': 1, 'is not boring': 7}


In [29]:
cvect = CountVectorizer(ngram_range=(1,2), stop_words='english')
print(cvect.fit_transform(text).toarray())
print(cvect.vocabulary_)

[[1 1 1 1 1 1 1]]
{'machine': 5, 'learning': 3, 'fun': 1, 'boring': 0, 'machine learning': 6, 'learning fun': 4, 'fun boring': 2}


In [31]:
cvect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 2),
 'preprocessor': None,
 'stop_words': 'english',
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

### TF-IDF Vectorizer

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'you know I want your love',
    'I like you',
    'what should I do'
]
count_vect = CountVectorizer()
print(count_vect.fit_transform(corpus).toarray())
print(count_vect.vocabulary_)

[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [33]:
tfdf_vect  = TfidfVectorizer()
print(tfdf_vect.fit_transform(corpus).toarray())
print(tfdf_vect.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [34]:
tfdf_vect.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': None,
 'min_df': 1,
 'ngram_range': (1, 1),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}