#  유방암 데이터 셋을 차원축소하기

In [76]:
import pandas as pd 
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
%matplotlib inline

In [77]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
df = pd.DataFrame(cancer.data, columns=cancer.feature_names)

In [78]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [79]:
cancer.target[:5] 

array([0, 0, 0, 0, 0])

In [80]:
# malignant = 악성 , benign = 양성
cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

### 정규화

In [81]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
cancer_std = scaler.fit_transform(cancer.data)

### PCA 변환 (10개의 차원)

In [82]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)

In [83]:
cancer_pca = pca.fit_transform(cancer_std)
cancer_pca[:5]

array([[ 9.19283683,  1.94858307, -1.12316616,  3.6337309 , -1.19511012,
         1.4114244 ,  2.15936937, -0.39840799, -0.15711654, -0.87739516],
       [ 2.3878018 , -3.76817174, -0.52929269,  1.11826386,  0.62177497,
         0.02865637,  0.01335778,  0.24099012, -0.71190342,  1.10700324],
       [ 5.73389628, -1.0751738 , -0.5517476 ,  0.91208267, -0.17708591,
         0.54145236, -0.66816373,  0.09737466,  0.02405846,  0.45424149],
       [ 7.1229532 , 10.27558912, -3.23278956,  0.15254704, -2.96087843,
         3.05342215,  1.42991444,  1.05956798, -1.40544908, -1.11701554],
       [ 3.93530207, -1.94807157,  1.38976673,  2.94063935,  0.54674741,
        -1.22649473, -0.93621367,  0.63637577, -0.263803  ,  0.37771848]])

In [84]:
cancer_pca_df = pd.DataFrame(cancer_pca, columns=['PC1','PC2','PC3','PC4','PC5','PC6','PC7','PC8','PC9','PC10'])
cancer_pca_df['target'] = cancer.target
cancer_pca_df.head()

PC1        PC2       PC3       PC4       PC5       PC6       PC7  \
0  9.192837   1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159369   
1  2.387802  -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013358   
2  5.733896  -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668164   
3  7.122953  10.275589 -3.232790  0.152547 -2.960878  3.053422  1.429914   
4  3.935302  -1.948072  1.389767  2.940639  0.546747 -1.226495 -0.936214   

        PC8       PC9      PC10  target  
0 -0.398408 -0.157117 -0.877395       0  
1  0.240990 -0.711903  1.107003       0  
2  0.097375  0.024058  0.454241       0  
3  1.059568 -1.405449 -1.117016       0  
4  0.636376 -0.263803  0.377718       0

### 분류

In [85]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [86]:
X_train, X_test, y_train, y_test = train_test_split(
    cancer_pca, cancer.target, stratify=cancer.target, test_size = 0.2, random_state=2021
)

### 평가

In [87]:
dtc = DecisionTreeClassifier(random_state=2021)
dtc.fit(X_train,y_train)
pred = dtc.predict(X_test)
print('분류 정확도: ', accuracy_score(y_test, pred))

분류 정확도:  0.9912280701754386


### PCA 변환 (5개의 차원)

In [88]:
pca = PCA(n_components=5)

In [89]:
cancer_pca = pca.fit_transform(cancer_std)
cancer_pca[:5]

array([[ 9.19283683,  1.94858309, -1.12316578,  3.63372951, -1.1951119 ],
       [ 2.3878018 , -3.76817176, -0.529293  ,  1.11826501,  0.62177692],
       [ 5.73389628, -1.07517379, -0.55174744,  0.91208206, -0.17708661],
       [ 7.1229532 , 10.27558911, -3.23278985,  0.1525479 , -2.96087994],
       [ 3.93530207, -1.94807157,  1.3897666 ,  2.94063979,  0.54674699]])

In [90]:
cancer_pca_df = pd.DataFrame(cancer_pca, columns=['PC1','PC2','PC3','PC4','PC5'])
cancer_pca_df['target'] = cancer.target
cancer_pca_df.head()

PC1        PC2       PC3       PC4       PC5  target
0  9.192837   1.948583 -1.123166  3.633730 -1.195112       0
1  2.387802  -3.768172 -0.529293  1.118265  0.621777       0
2  5.733896  -1.075174 -0.551747  0.912082 -0.177087       0
3  7.122953  10.275589 -3.232790  0.152548 -2.960880       0
4  3.935302  -1.948072  1.389767  2.940640  0.546747       0

In [91]:
X_train, X_test, y_train, y_test = train_test_split(
    cancer_pca, cancer.target, stratify=cancer.target, test_size = 0.2, random_state=2021
)

In [92]:
dtc = DecisionTreeClassifier(random_state=2021)
dtc.fit(X_train,y_train)
pred = dtc.predict(X_test)
print('분류 정확도: ', accuracy_score(y_test, pred))

분류 정확도:  0.9649122807017544


### PCA 변환 (2개의 차원)

In [93]:
pca = PCA(n_components=2)
cancer_pca = pca.fit_transform(cancer_std)
cancer_pca[:5]

array([[ 9.19283683,  1.94858307],
       [ 2.3878018 , -3.76817174],
       [ 5.73389628, -1.0751738 ],
       [ 7.1229532 , 10.27558912],
       [ 3.93530207, -1.94807157]])

In [94]:
cancer_pca_df = pd.DataFrame(cancer_pca, columns=['PC1','PC2'])
cancer_pca_df['target'] = cancer.target
cancer_pca_df.head()

PC1        PC2  target
0  9.192837   1.948583       0
1  2.387802  -3.768172       0
2  5.733896  -1.075174       0
3  7.122953  10.275589       0
4  3.935302  -1.948072       0

In [95]:
X_train, X_test, y_train, y_test = train_test_split(
    cancer_pca, cancer.target, stratify=cancer.target, test_size = 0.2, random_state=2021
)

In [96]:
dtc = DecisionTreeClassifier(random_state=2021)
dtc.fit(X_train,y_train)
pred = dtc.predict(X_test)
print('분류 정확도: ', accuracy_score(y_test, pred))

분류 정확도:  0.9210526315789473


#### 2차원에서는 정확도가 확 떨어진 것을 확인 할 수 있다.

### PCA변환 (30차원)

In [97]:
pca = PCA(n_components=30)
cancer_pca = pca.fit_transform(cancer_std)
cancer_pca[:1]

array([[ 9.19283683,  1.94858307, -1.12316616,  3.6337309 , -1.19511012,
         1.41142445,  2.15936987, -0.39840723, -0.15711836, -0.87740188,
         0.26295546, -0.85901448,  0.10338766, -0.6908041 , -0.60179313,
         0.74511579, -0.26547078, -0.54956269, -0.1337675 ,  0.3455649 ,
         0.09651489,  0.06884992,  0.08451859, -0.17525628, -0.15102006,
        -0.20150345, -0.25258499, -0.03391445,  0.04564772, -0.04716921]])

In [98]:
X_train, X_test, y_train, y_test = train_test_split(
    cancer_pca, cancer.target, stratify=cancer.target, test_size = 0.2, random_state=2021
)

In [113]:
dtc = DecisionTreeClassifier(random_state=2021)
dtc.fit(X_train,y_train)
pred = dtc.predict(X_test)
print('분류 정확도: ', accuracy_score(y_test, pred))

분류 정확도:  0.9473684210526315


#### 차원이 높다고 정확도가 높은 것은 아닌것 같다